version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    working_dir: /var/www
    tty: true
    volumes:
      - ./../blog:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
    networks:
      static:
        ipv4_address: 10.0.0.10

  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    container_name: web
    depends_on:
      - redis
      - database
    working_dir: /var/www
    volumes:
      - ./../blog:/var/www
    ports:
      - 8080:80
    networks:
      static:
        ipv4_address: 10.0.0.20

  database:
    image: mysql:5.7
    container_name: database
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=db_blog"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=root"
      - "MYSQL_ROOT_PASSWORD=root"
    ports:
      - "33061:3306"
    networks:
      static:
        ipv4_address: 10.0.0.30

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379"
    networks:
      static:
        ipv4_address: 10.0.0.40

#Docker Networks
networks:
  static:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/24

#Volumes
volumes:
  dbdata:
